defaults: &defaults
  app_path: "/"
  assets_url_base: "//www.local.malmo.se:3001/assets/"
  omniauth:
    github_team: 123
    github_key: abc
    github_secret: def
  siteseeker_autocomplete_url: "http://account_name.appliance.siteseeker.se/qc/index_name/qc"
  siteseeker:
    account: account_name
    index: index_name

development:
  <<: *defaults
  cache_ttl: 1
  max_age: 0
  title_suffix: "Malmö stad (utveckling)"

test:
  <<: *defaults
  cache_ttl: 43200
  max_age: 14400
  title_suffix: "Malmö stad (test)"

production: &production
  <<: *defaults
  assets_url_base: "//assets.malmo.se/external/v4/"
  cache_ttl: 43200
  max_age: 14400
  title_suffix: "Malmö stad"

staging:
  <<: *production
  title_suffix: "Malmö stad (staging)"
  assets_url_base: "//assets.malmo.se/external/v4-staging/"
